const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let compiled=null,node=null,d1=null,d2=null,a=1,h=1,gesture=0,cameraRunning=false,stream=null,raf=null,processing=false,lastInfer=0;
function finite(v){return typeof v==='number'&&Number.isFinite(v)}
function evalF(x){try{let v=compiled.evaluate({x});return finite(v)?v:NaN}catch{return NaN}}
function der(n,x){try{let v=n.compile().evaluate({x});return finite(v)?v:NaN}catch{return NaN}}
function apply(){let raw=$('fn').value.trim();try{node=math.parse(raw);compiled=node.compile();let test=0;for(let x=-5;x<=5;x+=.25)try{if(finite(compiled.evaluate({x})))test++}catch{}if(test<4)throw Error('No hay suficientes valores reales en [-5,5].');d1=math.derivative(node,'x');d2=math.derivative(d1,'x');$('fx').textContent=node.toString();$('d1').textContent=d1.toString();$('d2').textContent=d2.toString();$('error').textContent='';draw();update()}catch(e){$('error').textContent='Función no válida o no evaluable en el rango. Revisa sintaxis y dominio.'}}
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050505);const cam=new THREE.OrthographicCamera(-7,7,7,-7,.1,100);cam.position.z=10;const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(800,500);$('graph').appendChild(renderer.domElement);let graphGroup=new THREE.Group();scene.add(graphGroup);function line(points,color){let g=new THREE.BufferGeometry().setFromPoints(points),m=new THREE.LineBasicMaterial({color});return new THREE.Line(g,m)}function clear(){while(graphGroup.children.length){let o=graphGroup.children.pop();o.geometry?.dispose();o.material?.dispose()}}function draw(){clear();let pts=[];for(let x=-7;x<=7;x+=.035){let y=evalF(x);if(finite(y)&&Math.abs(y)<25)pts.push(new THREE.Vector3(x,y,0))}if(pts.length>1)graphGroup.add(line(pts,0xffffff));graphGroup.add(line([new THREE.Vector3(-7,0,0),new THREE.Vector3(7,0,0)],0x52525b),line([new THREE.Vector3(0,-7,0),new THREE.Vector3(0,7,0)],0x52525b))}function point(x,y){if(!finite(y))return;let m=new THREE.Mesh(new THREE.SphereGeometry(.12,14,14),new THREE.MeshBasicMaterial({color:0xef4444}));m.position.set(x,y,.1);graphGroup.add(m)}function segment(x1,y1,x2,y2){graphGroup.add(line([new THREE.Vector3(x1,y1,.05),new THREE.Vector3(x2,y2,.05)],0xef4444))}
function criticals(){let out=[];for(let x=-6.5;x<6.5;x+=.08){let p=der(d1,x),q=der(d1,x+.08);if(finite(p)&&finite(q)&&p*q<=0){let r=x+.04;for(let k=0;k<8;k++){let f=der(d1,r),fp=der(d2,r);if(!finite(f)||!finite(fp)||Math.abs(fp)<1e-7)break;r-=f/fp}if(!out.some(v=>Math.abs(v-r)<.15))out.push(r)}}return out}
function update(){if(!compiled)return;draw();let y,s,b,yb,q,cs;switch(gesture){case 1:y=evalF(a);s=der(d1,a);$('mode').textContent='1 dedo · Evaluación y pendiente';$('result').innerHTML=`x=a=${a.toFixed(2)} · f(a)=<b>${finite(y)?y.toFixed(4):'—'}</b> · f′(a)=<b>${finite(s)?s.toFixed(4):'—'}</b>`;point(a,y);if(finite(y)&&finite(s))segment(a-1,y-s,a+1,y+s);break;case 2:b=clamp(a+h,-6.5,6.5);y=evalF(a);yb=evalF(b);q=(yb-y)/(b-a);$('mode').textContent='2 dedos · Recta secante';$('result').innerHTML=`P₁=(${a.toFixed(2)},${finite(y)?y.toFixed(3):'—'}) · P₂=(${b.toFixed(2)},${finite(yb)?yb.toFixed(3):'—'}) · Δf/Δx=<b>${finite(q)?q.toFixed(4):'—'}</b>`;point(a,y);point(b,yb);if(finite(y)&&finite(yb))segment(a,y,b,yb);break;case 3:$('mode').textContent='3 dedos · Función y derivadas';$('result').innerHTML=`f(x)=<b>${node}</b><br>f′(x)=<b>${d1}</b><br>f″(x)=<b>${d2}</b>`;break;case 4:cs=criticals();$('mode').textContent='4 dedos · Máximos, mínimos y críticos';if(!cs.length){$('result').textContent='No se encontraron puntos críticos en el intervalo.';break}let arr=[];cs.forEach(x=>{let yy=evalF(x),dd=der(d2,x),t=dd<-.001?'Máximo local':dd>.001?'Mínimo local':'Punto crítico';arr.push(`${t}: x=${x.toFixed(3)}, f(x)=${finite(yy)?yy.toFixed(3):'—'}`);point(x,yy)});$('result').innerHTML=arr.join('<br>');break;case 5:let x0=2,dx=.5,y0=evalF(x0),y5=evalF(x0+dx),delta=y5-y0,lin=der(d1,x0)*dx;$('mode').textContent='5 dedos · Reto aplicado';$('result').innerHTML=`Si x aumenta ${dx}: Δf exacto=<b>${finite(delta)?delta.toFixed(4):'—'}</b> · aproximación lineal=<b>${finite(lin)?lin.toFixed(4):'—'}</b>`;break;default:$('mode').textContent='Espera un gesto';$('result').textContent='Levanta de 1 a 5 dedos.'}}
function count(l){let c=0;[[8,6],[12,10],[16,14],[20,18]].forEach(([t,p])=>{if(l[t].y<l[p].y-.02)c++});let w=l[0],dt=Math.hypot(l[4].x-w.x,l[4].y-w.y),di=Math.hypot(l[3].x-w.x,l[3].y-w.y);if(dt>di*1.1)c++;return c}
const video=$('video'),overlay=$('overlay'),ctx=overlay.getContext('2d'),hands=new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});hands.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.62,minTrackingConfidence:.62});hands.onResults(r=>{if(!cameraRunning)return;overlay.width=video.videoWidth||640;overlay.height=video.videoHeight||480;ctx.clearRect(0,0,overlay.width,overlay.height);if(r.multiHandLandmarks?.length){let lm=r.multiHandLandmarks[0],n=count(lm);drawConnectors(ctx,lm,HAND_CONNECTIONS,{color:'#ef4444',lineWidth:2});drawLandmarks(ctx,lm,{color:'#fff',lineWidth:1,radius:3});$('gesture').textContent=n+' dedo'+(n===1?'':'s')+' detectado'+(n===1?'':'s');if(n>=1&&n<=5){gesture=n;update()}}else{$('gesture').textContent='Sin mano'}});
async function tick(now){if(!cameraRunning)return;raf=requestAnimationFrame(tick);if(processing||video.readyState<2||!video.videoWidth||now-lastInfer<70)return;lastInfer=now;processing=true;try{await hands.send({image:video})}finally{processing=false}}
async function camera(){if(cameraRunning){stop();return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=stream;await video.play();cameraRunning=true;$('cameraBtn').textContent='⏹ Desactivar cámara';$('camMsg').style.display='none';$('status').textContent='Cámara activa';raf=requestAnimationFrame(tick)}catch(e){$('status').textContent='No se pudo activar la cámara';$('camMsg').textContent='Permite la cámara y usa HTTPS/GitHub Pages.'}}
function stop(){cameraRunning=false;if(raf)cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;$('cameraBtn').textContent='📷 Activar cámara';$('status').textContent='Cámara desactivada';$('camMsg').style.display='grid';gesture=0;update()}
$('cameraBtn').onclick=camera;$('apply').onclick=apply;$('ar').oninput=e=>{a=+e.target.value;$('av').textContent=a.toFixed(2);update()};$('reset').onclick=()=>{a=1;h=1;gesture=0;$('ar').value=1;$('av').textContent='1.00';update()};$('fn').onkeydown=e=>{if(e.key==='Enter')apply()};document.onkeydown=e=>{if(e.target.tagName==='INPUT')return;if(/^[1-5]$/.test(e.key)){gesture=+e.key;update()}if(e.key==='0'){gesture=0;update()}if(e.key==='ArrowLeft'){a=clamp(a-.1,-5,5);$('ar').value=a;$('av').textContent=a.toFixed(2);update()}if(e.key==='ArrowRight'){a=clamp(a+.1,-5,5);$('ar').value=a;$('av').textContent=a.toFixed(2);update()}if(e.key==='['){h=clamp(h-.1,.1,3);update()}if(e.key===']'){h=clamp(h+.1,.1,3);update()}};window.onresize=()=>{renderer.setSize($('graph').clientWidth,$('graph').clientHeight);let ar=$('graph').clientWidth/$('graph').clientHeight;cam.left=-7*ar;cam.right=7*ar;cam.updateProjectionMatrix()};function loop(){requestAnimationFrame(loop);renderer.render(scene,cam)}apply();loop();
