let compiled, d1, d2, fnText='x^2', a=1.5, mode=0, stream=null, cameraRunning=false, processing=false, lastGesture='', stable=0, fistSince=0;
const $=id=>document.getElementById(id), fmt=n=>Number.isFinite(n)?(Math.abs(n)<1e-8?0:n).toFixed(3):'indefinida';
function val(expr,x){try{let n=expr.evaluate({x});return typeof n==='number'&&Number.isFinite(n)?n:NaN}catch{return NaN}}function f(x){return val(compiled,x)}function df(x){return val(d1,x)}function ddf(x){return val(d2,x)}
function applyFunction(){try{fnText=$('fnInput').value.trim().replaceAll('sen(','sin(');let node=math.parse(fnText);compiled=node.compile();d1=math.derivative(node,'x');d2=math.derivative(d1,'x');$('error').textContent='';$('fnLabel').textContent='f(x)='+node.toString();$('derivLabel').textContent=`f'(x)=${d1.toString()} · f''(x)=${d2.toString()}`;rebuild();update()}catch(e){$('error').textContent='Función no válida. Ej.: x^2, sin(x), exp(x), 1/x';}}
$('apply').onclick=applyFunction;$('fnInput').addEventListener('keydown',e=>{if(e.key==='Enter')applyFunction()});document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{$('fnInput').value=b.dataset.f;applyFunction()});
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));const scene=new THREE.Scene();scene.background=new THREE.Color(0x05070c);const camera=new THREE.PerspectiveCamera(50,1,.1,100);camera.position.set(8,7,10);camera.lookAt(0,1,0);scene.add(new THREE.AmbientLight(0xffffff,1.7));scene.add(new THREE.GridHelper(14,28,0x344155,0x1a2230));scene.add(new THREE.AxesHelper(5));const group=new THREE.Group();scene.add(group);
function makeLine(fn,color){let pts=[];for(let x=-5;x<=5;x+=.035){let y=fn(x);if(Number.isFinite(y)&&Math.abs(y)<12)pts.push(new THREE.Vector3(x,y,0));}return new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color}));}let curve,tangent,derivative,second;function replace(old,n){if(old){group.remove(old);old.geometry.dispose();old.material.dispose()}group.add(n);return n}function rebuild(){if(!compiled)return;curve=replace(curve,makeLine(f,0x6ee7ff));derivative=replace(derivative,makeLine(df,0xc891ff));second=replace(second,makeLine(ddf,0xffffff));derivative.visible=second.visible=false;drawTangent()}
const dot=new THREE.Mesh(new THREE.SphereGeometry(.13,18,18),new THREE.MeshBasicMaterial({color:0xffffff}));scene.add(dot);const critGroup=new THREE.Group();scene.add(critGroup);const positions=new Float32Array(900*3);for(let i=0;i<900;i++){let t=Math.random()*Math.PI*2,r=5+Math.random()*5;positions[i*3]=Math.cos(t)*r;positions[i*3+1]=(Math.random()-.5)*6;positions[i*3+2]=Math.sin(t)*r}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(positions,3));const particles=new THREE.Points(pg,new THREE.PointsMaterial({color:0x6ee7ff,size:.035,transparent:true,opacity:.7}));scene.add(particles);
function drawTangent(){if(!compiled)return;let m=df(a),y=f(a);if(!Number.isFinite(m)||!Number.isFinite(y)){if(tangent)tangent.visible=false;return}tangent=replace(tangent,makeLine(x=>m*(x-a)+y,0xffbd6e));tangent.visible=mode===2}
function criticals(){let out=[],step=10/500,prev=-5,pv=df(prev);for(let x=-5+step;x<=5;x+=step){let v=df(x);if(Number.isFinite(pv)&&Number.isFinite(v)&&pv*v<=0){let r=x-step/2;for(let i=0;i<10;i++){let q=df(r),dd=ddf(r);if(!Number.isFinite(q)||!Number.isFinite(dd)||Math.abs(dd)<1e-8)break;r-=q/dd}if(Math.abs(df(r))<.05&&!out.some(z=>Math.abs(z-r)<.15))out.push(r)}prev=x;pv=v}return out}
function updateCriticals(){critGroup.clear();if(mode!==4)return;criticals().forEach(x=>{let y=f(x);if(Number.isFinite(y)){let m=new THREE.Mesh(new THREE.SphereGeometry(.16,16,16),new THREE.MeshBasicMaterial({color:0xff7a90}));m.position.set(x,y,0);critGroup.add(m)}})}
function setMode(n){mode=n;const names=['Vista inicial','Índice: mover punto','Pinza: recta tangente','Mano abierta: derivadas','Dos dedos: puntos críticos','Puño: reiniciar'];$('gestureTitle').textContent=names[n]||names[0];const info=['Usa un gesto para interactuar.','Mueve la mano horizontalmente.','Mantén pulgar e índice juntos.','Función y derivadas visibles.','Puntos críticos aproximados en el rango.','Vista reiniciada.'];$('gestureInfo').textContent=info[n]||info[0];update()}
function update(){if(!compiled)return;dot.position.set(a,f(a),0);dot.visible=mode!==4;derivative.visible=second.visible=mode===3;drawTangent();updateCriticals();$('result').textContent=`a=${fmt(a)} · f(a)=${fmt(f(a))} · f'(a)=${fmt(df(a))}`}
function reset(){a=1.5;setMode(0)}$('reset').onclick=reset;addEventListener('keydown',e=>{if('12345'.includes(e.key))setMode(+e.key);if(e.key==='ArrowLeft'){a-=.1;update()}if(e.key==='ArrowRight'){a+=.1;update()}if(e.key.toLowerCase()==='r')reset()});let drag=false,lx=0;$('scene').addEventListener('pointerdown',e=>{drag=true;lx=e.clientX});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag){a=Math.max(-4.8,Math.min(4.8,a+(e.clientX-lx)*.015));lx=e.clientX;update()}});
function resize(){let w=$('scene').clientWidth,h=$('scene').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);function animate(){requestAnimationFrame(animate);particles.rotation.y+=.0006;renderer.render(scene,camera)}animate();
// MediaPipe: draw the hand skeleton and recognize pose + movement.
const video=$('video'), hc=$('handCanvas'), ctx=hc.getContext('2d');function dist(p,q){return Math.hypot(p.x-q.x,p.y-q.y)}function fingerCount(lm){let c=0;if(dist(lm[4],lm[0])>dist(lm[3],lm[0])*1.08)c++;[[8,6],[12,10],[16,14],[20,18]].forEach(([t,p])=>{if(lm[t].y<lm[p].y-.015)c++});return c}function isPinch(lm){return dist(lm[4],lm[8])<.07}function isPointing(lm){return lm[8].y<lm[6].y&&lm[12].y>lm[10].y&&lm[16].y>lm[14].y&&lm[20].y>lm[18].y}function isFist(lm){return [8,12,16,20].every((t,i)=>dist(lm[t],lm[0])<dist(lm[[6,10,14,18][i]],lm[0])*1.08)}
const hands=new Hands({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`});hands.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.65,minTrackingConfidence:.6});hands.onResults(res=>{if(!cameraRunning)return;hc.width=video.videoWidth||640;hc.height=video.videoHeight||480;ctx.clearRect(0,0,hc.width,hc.height);if(!res.multiHandLandmarks?.length){$('gestureInfo').textContent='Muestra la mano completa a la cámara.';return}const lm=res.multiHandLandmarks[0];drawConnectors(ctx,lm,HAND_CONNECTIONS,{color:'#6ee7ff',lineWidth:3});drawLandmarks(ctx,lm,{color:'#ffffff',lineWidth:2,radius:3});let gesture='';if(isPinch(lm))gesture='pinch';else if(isFist(lm))gesture='fist';else if(isPointing(lm))gesture='point';else if(fingerCount(lm)>=4)gesture='open';else if(fingerCount(lm)===2)gesture='two';if(gesture===lastGesture)stable++;else{lastGesture=gesture;stable=0}if(stable>=2){if(gesture==='pinch')setMode(2);else if(gesture==='open')setMode(3);else if(gesture==='two')setMode(4);else if(gesture==='fist'){if(!fistSince)fistSince=Date.now();if(Date.now()-fistSince>900)reset()}else fistSince=0}if(gesture==='point'){setMode(1);a=(.5-lm[8].x)*9.5;update()}$('gestureInfo').textContent=`Gesto detectado: ${({pinch:'pinza · tangente',fist:'puño · reiniciar',point:'índice · mover punto',open:'mano abierta · derivadas',two:'dos dedos · puntos críticos'})[gesture]||'mano detectada'}`});
$('cameraBtn').onclick=async()=>{if(cameraRunning){stopCamera();return}try{if(!navigator.mediaDevices?.getUserMedia)throw Error('El navegador no permite cámara. Abre la web con HTTPS.');stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:640},height:{ideal:480},facingMode:'user'},audio:false});video.srcObject=stream;await video.play();cameraRunning=true;$('cameraBtn').textContent='⏹ Desactivar cámara';$('status').textContent='🟢 Cámara activa · buscando mano';frame()}catch(e){console.error(e);$('status').textContent='🔴 Error de cámara';alert(e.name==='NotAllowedError'?'Permite el acceso a la cámara en los ajustes del navegador y recarga la página.':`No se pudo activar la cámara: ${e.message}`)}};
let raf, busy=false;async function frame(){if(!cameraRunning)return;if(video.readyState>=2&&!busy){busy=true;try{await hands.send({image:video})}catch(e){console.error(e)}busy=false}raf=requestAnimationFrame(frame)}function stopCamera(){cameraRunning=false;cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;$('cameraBtn').textContent='📷 Activar cámara';$('status').textContent='🔴 Cámara desactivada';ctx.clearRect(0,0,hc.width,hc.height)}
applyFunction();
